apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
patchesStrategicMerge:
- web.yml
- scheduler.yml
patches:
- path: ingress_patch.yml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: airflow
    namespace: airflow