apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: airflow
  name: airflow-web
spec:
  replicas: 2
  template:
    spec:
      containers:
         - name: airflow-web
           image: airlfow/prod/code:latest
           resources:
             requests:
               cpu: 90m
               memory: 900Mi
             limits:
               cpu: 1000m
               memory: 1500M